### PR TITLE
Add Livebook

### PR DESCRIPTION
**Pull request by ndrean**
Can you review the addition of Livebook?

added the ".livemd" file
modified Readme to handle Livebook.
-> the contents: added install / Livebook
-> In the "how" paragraph, added a button link to Fly.io + howto
-> a Livebook install + a button to upload and run the Livebook locally

Nb: the links should be tested. I rewrote them targetting the futur repo but still need to check.

### CODE REVIEW

**Comment by ndrean** [comment]
I have added a mermaid diagram for the process message passing, some sequence diagram and a plot to visualize computation time.

**Comment by nelsonic** [comment]
@ndrean I've had a quick look and LGTM! 👌 
Once you feel that the PR is ready for review, feel free to assign and I will do a bit more in-depth look. 🧑‍💻

**Comment by ndrean** [comment]
A Javascripter friend of mine had a quick look and challenged me with the ordering of some concepts that were not clear to him, so I went through quite a few little modifications: re-ordering in a way that concepts and notations aren't used before being defined, and little developments. Although I tried to follow closely the original work though, it is an opinionated try :)

The Fly.io Livebook can be modified as well, I guess it is open.

**Review by nelsonic — APPROVED** [review]
Great additions @ndrean 🎉

**Pull request merged**
