### PR TITLE
adds section about process to the readme

### PR DESCRIPTION
**Pull request by RobStallion**
adds section about process to the readme #99

### CODE REVIEW

**Comment by nelsonic** [comment]
@RobStallion looking good. 👀 📝 👍

**Comment by iteles** [comment]
@VirtualDOMinic Thanks for the catch! 🎉

**Comment by RobStallion** [comment]
@VirtualDOMinic Thanks for pointing those out. I'll update them now. 👍

**Comment by RobStallion** [comment]
I have just added the awaiting-review label. @VirtualDOMinic please also feel free to add a review.

**Pull request merged**
