### PR TITLE
Add what, why, how & installation basics for Elixir

### PR DESCRIPTION
**Pull request by katbow**

### CODE REVIEW

**Comment by iteles** [comment]
@katbow You should have enough permissions to assign this PR to someone for review when you think it's ready - do you?

**Comment by katbow** [comment]
Nope, can't assign right now :cry:

**Comment by nelsonic** [comment]
@katbow you should have write-access to the repo and be able to assign, please _confirm_ (_thanks_!)

**Comment by katbow** [comment]
Yup, it's there now!

**Comment by nelsonic** [comment]
amaze! thanks! merging! ❤️  ✅   🎉

**Pull request merged**
